channels:
- conda-forge
dependencies:
- python=3.7
- pip
# dependencies
- numpy
- geopy
- matplotlib-base
- mercantile
- pillow
- rasterio
- requests
- joblib
# additional
- geopandas
- pip:
  - git+https://github.com/geopandas/contextily.git@master
