"""
Tile providers.

This file is autogenerated! It is a python representation of the leaflet
providers defined by the leaflet-providers.js extension to Leaflet
(https://github.com/leaflet-extras/leaflet-providers).
Credit to the leaflet-providers.js  project (BSD 2-Clause "Simplified" License)
and the Leaflet Providers contributors.

Generated by parse_leaflet_providers.py at 2019-05-07 from leaflet-providers
at commit 2f76cf3100c5e0eb0a53def3ea3659f55e49d2b4 (Bumped version to 1.6.0).

"""


class Bunch(dict):
    """A dict with attribute-access"""

    def __getattr__(self, key):
        try:
            return self.__getitem__(key)
        except KeyError:
            raise AttributeError(key)

    def __dir__(self):
        return self.keys()


class TileProvider(Bunch):
    """
    A dict with attribute-access and that
    can be called to update keys
    """

    def __call__(self, **kwargs):
        new = self.copy()
        new.update(kwargs)
        return new


providers = Bunch(
    OpenStreetMap = Bunch(
        Mapnik = TileProvider(
            url = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            max_zoom = 19,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'OpenStreetMap.Mapnik'
        ),
        DE = TileProvider(
            url = 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png',
            max_zoom = 18,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'OpenStreetMap.DE'
        ),
        CH = TileProvider(
            url = 'https://tile.osm.ch/switzerland/{z}/{x}/{y}.png',
            max_zoom = 18,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            bounds = [[45, 5], [48, 11]],
            name = 'OpenStreetMap.CH'
        ),
        France = TileProvider(
            url = 'https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',
            max_zoom = 20,
            attribution = '&copy; Openstreetmap France | &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'OpenStreetMap.France'
        ),
        HOT = TileProvider(
            url = 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
            max_zoom = 19,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Tiles style by <a href="https://www.hotosm.org/" target="_blank">Humanitarian OpenStreetMap Team</a> hosted by <a href="https://openstreetmap.fr/" target="_blank">OpenStreetMap France</a>',
            name = 'OpenStreetMap.HOT'
        ),
        BZH = TileProvider(
            url = 'https://tile.openstreetmap.bzh/br/{z}/{x}/{y}.png',
            max_zoom = 19,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Tiles courtesy of <a href="http://www.openstreetmap.bzh/" target="_blank">Breton OpenStreetMap Team</a>',
            bounds = [[46.2, -5.5], [50, 0.7]],
            name = 'OpenStreetMap.BZH'
        )
    ),
    OpenSeaMap = TileProvider(
        url = 'https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png',
        attribution = 'Map data: &copy; <a href="http://www.openseamap.org">OpenSeaMap</a> contributors',
        name = 'OpenSeaMap'
    ),
    OpenPtMap = TileProvider(
        url = 'http://openptmap.org/tiles/{z}/{x}/{y}.png',
        max_zoom = 17,
        attribution = 'Map data: &copy; <a href="http://www.openptmap.org">OpenPtMap</a> contributors',
        name = 'OpenPtMap'
    ),
    OpenTopoMap = TileProvider(
        url = 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
        max_zoom = 17,
        attribution = 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
        name = 'OpenTopoMap'
    ),
    OpenRailwayMap = TileProvider(
        url = 'https://{s}.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png',
        max_zoom = 19,
        attribution = 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | Map style: &copy; <a href="https://www.OpenRailwayMap.org">OpenRailwayMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
        name = 'OpenRailwayMap'
    ),
    OpenFireMap = TileProvider(
        url = 'http://openfiremap.org/hytiles/{z}/{x}/{y}.png',
        max_zoom = 19,
        attribution = 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | Map style: &copy; <a href="http://www.openfiremap.org">OpenFireMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
        name = 'OpenFireMap'
    ),
    SafeCast = TileProvider(
        url = 'https://s3.amazonaws.com/te512.safecast.org/{z}/{x}/{y}.png',
        max_zoom = 16,
        attribution = 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | Map style: &copy; <a href="https://blog.safecast.org/about/">SafeCast</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
        name = 'SafeCast'
    ),
    Thunderforest = Bunch(
        OpenCycleMap = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'cycle',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.OpenCycleMap'
        ),
        Transport = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'transport',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.Transport'
        ),
        TransportDark = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'transport-dark',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.TransportDark'
        ),
        SpinalMap = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'spinal-map',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.SpinalMap'
        ),
        Landscape = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'landscape',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.Landscape'
        ),
        Outdoors = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'outdoors',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.Outdoors'
        ),
        Pioneer = TileProvider(
            url = 'https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}',
            attribution = '&copy; <a href="http://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'pioneer',
            apikey = '<insert your api key here>',
            max_zoom = 22,
            name = 'Thunderforest.Pioneer'
        )
    ),
    OpenMapSurfer = Bunch(
        Roads = TileProvider(
            url = 'https://maps.heigit.org/openmapsurfer/tiles/{variant}/webmercator/{z}/{x}/{y}.png',
            max_zoom = 19,
            variant = 'roads',
            attribution = 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'OpenMapSurfer.Roads'
        ),
        AdminBounds = TileProvider(
            url = 'https://maps.heigit.org/openmapsurfer/tiles/{variant}/webmercator/{z}/{x}/{y}.png',
            max_zoom = 18,
            variant = 'adminb',
            attribution = 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'OpenMapSurfer.AdminBounds'
        )
    ),
    Hydda = Bunch(
        Full = TileProvider(
            url = 'https://{s}.tile.openstreetmap.se/hydda/{variant}/{z}/{x}/{y}.png',
            max_zoom = 18,
            variant = 'full',
            attribution = 'Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'Hydda.Full'
        ),
        Base = TileProvider(
            url = 'https://{s}.tile.openstreetmap.se/hydda/{variant}/{z}/{x}/{y}.png',
            max_zoom = 18,
            variant = 'base',
            attribution = 'Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'Hydda.Base'
        ),
        RoadsAndLabels = TileProvider(
            url = 'https://{s}.tile.openstreetmap.se/hydda/{variant}/{z}/{x}/{y}.png',
            max_zoom = 18,
            variant = 'roads_and_labels',
            attribution = 'Tiles courtesy of <a href="http://openstreetmap.se/" target="_blank">OpenStreetMap Sweden</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            name = 'Hydda.RoadsAndLabels'
        )
    ),
    MapBox = TileProvider(
        url = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}{r}.png?access_token={accessToken}',
        attribution = '<a href="https://www.mapbox.com/about/maps/" target="_blank">&copy; Mapbox</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors <a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a>',
        subdomains = 'abcd',
        id = 'mapbox.streets',
        accessToken = '<insert your access token here>',
        name = 'MapBox'
    ),
    Stamen = Bunch(
        Toner = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner',
            ext = 'png',
            name = 'Stamen.Toner'
        ),
        TonerBackground = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner-background',
            ext = 'png',
            name = 'Stamen.TonerBackground'
        ),
        TonerHybrid = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner-hybrid',
            ext = 'png',
            name = 'Stamen.TonerHybrid'
        ),
        TonerLines = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner-lines',
            ext = 'png',
            name = 'Stamen.TonerLines'
        ),
        TonerLabels = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner-labels',
            ext = 'png',
            name = 'Stamen.TonerLabels'
        ),
        TonerLite = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toner-lite',
            ext = 'png',
            name = 'Stamen.TonerLite'
        ),
        Watercolor = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 1,
            max_zoom = 16,
            variant = 'watercolor',
            ext = 'jpg',
            name = 'Stamen.Watercolor'
        ),
        Terrain = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 18,
            variant = 'terrain',
            ext = 'png',
            name = 'Stamen.Terrain'
        ),
        TerrainBackground = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 18,
            variant = 'terrain-background',
            ext = 'png',
            name = 'Stamen.TerrainBackground'
        ),
        TopOSMRelief = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toposm-color-relief',
            ext = 'jpg',
            bounds = [[22, -132], [51, -56]],
            name = 'Stamen.TopOSMRelief'
        ),
        TopOSMFeatures = TileProvider(
            url = 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',
            attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains = 'abcd',
            min_zoom = 0,
            max_zoom = 20,
            variant = 'toposm-features',
            ext = 'png',
            bounds = [[22, -132], [51, -56]],
            opacity = 0.9,
            name = 'Stamen.TopOSMFeatures'
        )
    ),
    Esri = Bunch(
        WorldStreetMap = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Street_Map',
            attribution = 'Tiles &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012',
            name = 'Esri.WorldStreetMap'
        ),
        DeLorme = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'Specialty/DeLorme_World_Base_Map',
            attribution = 'Tiles &copy; Esri &mdash; Copyright: &copy;2012 DeLorme',
            min_zoom = 1,
            max_zoom = 11,
            name = 'Esri.DeLorme'
        ),
        WorldTopoMap = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Topo_Map',
            attribution = 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community',
            name = 'Esri.WorldTopoMap'
        ),
        WorldImagery = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Imagery',
            attribution = 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
            name = 'Esri.WorldImagery'
        ),
        WorldTerrain = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Terrain_Base',
            attribution = 'Tiles &copy; Esri &mdash; Source: USGS, Esri, TANA, DeLorme, and NPS',
            max_zoom = 13,
            name = 'Esri.WorldTerrain'
        ),
        WorldShadedRelief = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Shaded_Relief',
            attribution = 'Tiles &copy; Esri &mdash; Source: Esri',
            max_zoom = 13,
            name = 'Esri.WorldShadedRelief'
        ),
        WorldPhysical = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'World_Physical_Map',
            attribution = 'Tiles &copy; Esri &mdash; Source: US National Park Service',
            max_zoom = 8,
            name = 'Esri.WorldPhysical'
        ),
        OceanBasemap = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'Ocean_Basemap',
            attribution = 'Tiles &copy; Esri &mdash; Sources: GEBCO, NOAA, CHS, OSU, UNH, CSUMB, National Geographic, DeLorme, NAVTEQ, and Esri',
            max_zoom = 13,
            name = 'Esri.OceanBasemap'
        ),
        NatGeoWorldMap = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'NatGeo_World_Map',
            attribution = 'Tiles &copy; Esri &mdash; National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC',
            max_zoom = 16,
            name = 'Esri.NatGeoWorldMap'
        ),
        WorldGrayCanvas = TileProvider(
            url = 'https://server.arcgisonline.com/ArcGIS/rest/services/{variant}/MapServer/tile/{z}/{y}/{x}',
            variant = 'Canvas/World_Light_Gray_Base',
            attribution = 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ',
            max_zoom = 16,
            name = 'Esri.WorldGrayCanvas'
        )
    ),
    OpenWeatherMap = Bunch(
        Clouds = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'clouds',
            name = 'OpenWeatherMap.Clouds'
        ),
        CloudsClassic = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'clouds_cls',
            name = 'OpenWeatherMap.CloudsClassic'
        ),
        Precipitation = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'precipitation',
            name = 'OpenWeatherMap.Precipitation'
        ),
        PrecipitationClassic = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'precipitation_cls',
            name = 'OpenWeatherMap.PrecipitationClassic'
        ),
        Rain = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'rain',
            name = 'OpenWeatherMap.Rain'
        ),
        RainClassic = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'rain_cls',
            name = 'OpenWeatherMap.RainClassic'
        ),
        Pressure = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'pressure',
            name = 'OpenWeatherMap.Pressure'
        ),
        PressureContour = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'pressure_cntr',
            name = 'OpenWeatherMap.PressureContour'
        ),
        Wind = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'wind',
            name = 'OpenWeatherMap.Wind'
        ),
        Temperature = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'temp',
            name = 'OpenWeatherMap.Temperature'
        ),
        Snow = TileProvider(
            url = 'http://{s}.tile.openweathermap.org/map/{variant}/{z}/{x}/{y}.png?appid={apiKey}',
            max_zoom = 19,
            attribution = 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>',
            apiKey = '<insert your api key here>',
            opacity = 0.5,
            variant = 'snow',
            name = 'OpenWeatherMap.Snow'
        )
    ),
    HERE = Bunch(
        normalDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDay'
        ),
        normalDayCustom = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.custom',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayCustom'
        ),
        normalDayGrey = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.grey',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayGrey'
        ),
        normalDayMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayMobile'
        ),
        normalDayGreyMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.grey.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayGreyMobile'
        ),
        normalDayTransit = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.transit',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayTransit'
        ),
        normalDayTransitMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day.transit.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalDayTransitMobile'
        ),
        normalNight = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNight'
        ),
        normalNightMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNightMobile'
        ),
        normalNightGrey = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night.grey',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNightGrey'
        ),
        normalNightGreyMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night.grey.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNightGreyMobile'
        ),
        normalNightTransit = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night.transit',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNightTransit'
        ),
        normalNightTransitMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.night.transit.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.normalNightTransitMobile'
        ),
        reducedDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'reduced.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.reducedDay'
        ),
        reducedNight = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'reduced.night',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.reducedNight'
        ),
        basicMap = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day',
            max_zoom = 20,
            type = 'basetile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.basicMap'
        ),
        mapLabels = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'normal.day',
            max_zoom = 20,
            type = 'labeltile',
            language = 'eng',
            format = 'png',
            size = '256',
            name = 'HERE.mapLabels'
        ),
        trafficFlow = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'traffic',
            variant = 'normal.day',
            max_zoom = 20,
            type = 'flowtile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.trafficFlow'
        ),
        carnavDayGrey = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'carnav.day.grey',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.carnavDayGrey'
        ),
        hybridDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'hybrid.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.hybridDay'
        ),
        hybridDayMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'hybrid.day.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.hybridDayMobile'
        ),
        hybridDayTransit = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'hybrid.day.transit',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.hybridDayTransit'
        ),
        hybridDayGrey = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'hybrid.grey.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.hybridDayGrey'
        ),
        pedestrianDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'pedestrian.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.pedestrianDay'
        ),
        pedestrianNight = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'base',
            variant = 'pedestrian.night',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.pedestrianNight'
        ),
        satelliteDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'satellite.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.satelliteDay'
        ),
        terrainDay = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'terrain.day',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.terrainDay'
        ),
        terrainDayMobile = TileProvider(
            url = 'https://{s}.{base}.maps.api.here.com/maptile/2.1/{type}/{mapID}/{variant}/{z}/{x}/{y}/{size}/{format}?app_id={app_id}&app_code={app_code}&lg={language}',
            attribution = 'Map &copy; 1987-2019 <a href="http://developer.here.com">HERE</a>',
            subdomains = '1234',
            mapID = 'newest',
            app_id = '<insert your app_id here>',
            app_code = '<insert your app_code here>',
            base = 'aerial',
            variant = 'terrain.day.mobile',
            max_zoom = 20,
            type = 'maptile',
            language = 'eng',
            format = 'png8',
            size = '256',
            name = 'HERE.terrainDayMobile'
        )
    ),
    FreeMapSK = TileProvider(
        url = 'http://t{s}.freemap.sk/T/{z}/{x}/{y}.jpeg',
        min_zoom = 8,
        max_zoom = 16,
        subdomains = '1234',
        bounds = [[47.204642, 15.996093], [49.830896, 22.576904]],
        attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, vizualization CC-By-SA 2.0 <a href="http://freemap.sk">Freemap.sk</a>',
        name = 'FreeMapSK'
    ),
    MtbMap = TileProvider(
        url = 'http://tile.mtbmap.cz/mtbmap_tiles/{z}/{x}/{y}.png',
        attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &amp; USGS',
        name = 'MtbMap'
    ),
    CartoDB = Bunch(
        Positron = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'light_all',
            name = 'CartoDB.Positron'
        ),
        PositronNoLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'light_nolabels',
            name = 'CartoDB.PositronNoLabels'
        ),
        PositronOnlyLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'light_only_labels',
            name = 'CartoDB.PositronOnlyLabels'
        ),
        DarkMatter = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'dark_all',
            name = 'CartoDB.DarkMatter'
        ),
        DarkMatterNoLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'dark_nolabels',
            name = 'CartoDB.DarkMatterNoLabels'
        ),
        DarkMatterOnlyLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'dark_only_labels',
            name = 'CartoDB.DarkMatterOnlyLabels'
        ),
        Voyager = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'rastertiles/voyager',
            name = 'CartoDB.Voyager'
        ),
        VoyagerNoLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'rastertiles/voyager_nolabels',
            name = 'CartoDB.VoyagerNoLabels'
        ),
        VoyagerOnlyLabels = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'rastertiles/voyager_only_labels',
            name = 'CartoDB.VoyagerOnlyLabels'
        ),
        VoyagerLabelsUnder = TileProvider(
            url = 'https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png',
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains = 'abcd',
            max_zoom = 19,
            variant = 'rastertiles/voyager_labels_under',
            name = 'CartoDB.VoyagerLabelsUnder'
        )
    ),
    HikeBike = Bunch(
        HikeBike = TileProvider(
            url = 'https://tiles.wmflabs.org/{variant}/{z}/{x}/{y}.png',
            max_zoom = 19,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'hikebike',
            name = 'HikeBike.HikeBike'
        ),
        HillShading = TileProvider(
            url = 'https://tiles.wmflabs.org/{variant}/{z}/{x}/{y}.png',
            max_zoom = 15,
            attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            variant = 'hillshading',
            name = 'HikeBike.HillShading'
        )
    ),
    BasemapAT = Bunch(
        basemap = TileProvider(
            url = 'https://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.{format}',
            max_zoom = 20,
            attribution = 'Datenquelle: <a href="https://www.basemap.at">basemap.at</a>',
            subdomains = ['', '1', '2', '3', '4'],
            format = 'png',
            bounds = [[46.35877, 8.782379], [49.037872, 17.189532]],
            variant = 'geolandbasemap',
            name = 'BasemapAT.basemap'
        ),
        grau = TileProvider(
            url = 'https://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.{format}',
            max_zoom = 19,
            attribution = 'Datenquelle: <a href="https://www.basemap.at">basemap.at</a>',
            subdomains = ['', '1', '2', '3', '4'],
            format = 'png',
            bounds = [[46.35877, 8.782379], [49.037872, 17.189532]],
            variant = 'bmapgrau',
            name = 'BasemapAT.grau'
        ),
        overlay = TileProvider(
            url = 'https://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.{format}',
            max_zoom = 19,
            attribution = 'Datenquelle: <a href="https://www.basemap.at">basemap.at</a>',
            subdomains = ['', '1', '2', '3', '4'],
            format = 'png',
            bounds = [[46.35877, 8.782379], [49.037872, 17.189532]],
            variant = 'bmapoverlay',
            name = 'BasemapAT.overlay'
        ),
        highdpi = TileProvider(
            url = 'https://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.{format}',
            max_zoom = 19,
            attribution = 'Datenquelle: <a href="https://www.basemap.at">basemap.at</a>',
            subdomains = ['', '1', '2', '3', '4'],
            format = 'jpeg',
            bounds = [[46.35877, 8.782379], [49.037872, 17.189532]],
            variant = 'bmaphidpi',
            name = 'BasemapAT.highdpi'
        ),
        orthofoto = TileProvider(
            url = 'https://maps{s}.wien.gv.at/basemap/{variant}/normal/google3857/{z}/{y}/{x}.{format}',
            max_zoom = 20,
            attribution = 'Datenquelle: <a href="https://www.basemap.at">basemap.at</a>',
            subdomains = ['', '1', '2', '3', '4'],
            format = 'jpeg',
            bounds = [[46.35877, 8.782379], [49.037872, 17.189532]],
            variant = 'bmaporthofoto30cm',
            name = 'BasemapAT.orthofoto'
        )
    ),
    nlmaps = Bunch(
        standaard = TileProvider(
            url = 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts/{variant}/EPSG:3857/{z}/{x}/{y}.png',
            min_zoom = 6,
            max_zoom = 19,
            bounds = [[50.5, 3.25], [54, 7.6]],
            attribution = 'Kaartgegevens &copy; <a href="kadaster.nl">Kadaster</a>',
            variant = 'brtachtergrondkaart',
            name = 'nlmaps.standaard'
        ),
        pastel = TileProvider(
            url = 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts/{variant}/EPSG:3857/{z}/{x}/{y}.png',
            min_zoom = 6,
            max_zoom = 19,
            bounds = [[50.5, 3.25], [54, 7.6]],
            attribution = 'Kaartgegevens &copy; <a href="kadaster.nl">Kadaster</a>',
            variant = 'brtachtergrondkaartpastel',
            name = 'nlmaps.pastel'
        ),
        grijs = TileProvider(
            url = 'https://geodata.nationaalgeoregister.nl/tiles/service/wmts/{variant}/EPSG:3857/{z}/{x}/{y}.png',
            min_zoom = 6,
            max_zoom = 19,
            bounds = [[50.5, 3.25], [54, 7.6]],
            attribution = 'Kaartgegevens &copy; <a href="kadaster.nl">Kadaster</a>',
            variant = 'brtachtergrondkaartgrijs',
            name = 'nlmaps.grijs'
        ),
        luchtfoto = TileProvider(
            url = 'https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts/1.0.0/2016_ortho25/EPSG:3857/{z}/{x}/{y}.png',
            min_zoom = 6,
            max_zoom = 19,
            bounds = [[50.5, 3.25], [54, 7.6]],
            attribution = 'Kaartgegevens &copy; <a href="kadaster.nl">Kadaster</a>',
            name = 'nlmaps.luchtfoto'
        )
    ),
    NASAGIBS = Bunch(
        ModisTerraTrueColorCR = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 9,
            format = 'jpg',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_CorrectedReflectance_TrueColor',
            name = 'NASAGIBS.ModisTerraTrueColorCR'
        ),
        ModisTerraBands367CR = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 9,
            format = 'jpg',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_CorrectedReflectance_Bands367',
            name = 'NASAGIBS.ModisTerraBands367CR'
        ),
        ViirsEarthAtNight2012 = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 8,
            format = 'jpg',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'VIIRS_CityLights_2012',
            name = 'NASAGIBS.ViirsEarthAtNight2012'
        ),
        ModisTerraLSTDay = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 7,
            format = 'png',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_Land_Surface_Temp_Day',
            opacity = 0.75,
            name = 'NASAGIBS.ModisTerraLSTDay'
        ),
        ModisTerraSnowCover = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 8,
            format = 'png',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_Snow_Cover',
            opacity = 0.75,
            name = 'NASAGIBS.ModisTerraSnowCover'
        ),
        ModisTerraAOD = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 6,
            format = 'png',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_Aerosol',
            opacity = 0.75,
            name = 'NASAGIBS.ModisTerraAOD'
        ),
        ModisTerraChlorophyll = TileProvider(
            url = 'https://map1.vis.earthdata.nasa.gov/wmts-webmerc/{variant}/default/{time}/{tilematrixset}{maxZoom}/{z}/{y}/{x}.{format}',
            attribution = 'Imagery provided by services from the Global Imagery Browse Services (GIBS), operated by the NASA/GSFC/Earth Science Data and Information System (<a href="https://earthdata.nasa.gov">ESDIS</a>) with funding provided by NASA/HQ.',
            bounds = [[-85.0511287776, -179.999999975], [85.0511287776, 179.999999975]],
            min_zoom = 1,
            max_zoom = 7,
            format = 'png',
            time = '',
            tilematrixset = 'GoogleMapsCompatible_Level',
            variant = 'MODIS_Terra_Chlorophyll_A',
            opacity = 0.75,
            name = 'NASAGIBS.ModisTerraChlorophyll'
        )
    ),
    NLS = TileProvider(
        url = 'https://nls-{s}.tileserver.com/nls/{z}/{x}/{y}.jpg',
        attribution = '<a href="http://geo.nls.uk/maps/">National Library of Scotland Historic Maps</a>',
        bounds = [[49.6, -12], [61.7, 3]],
        min_zoom = 1,
        max_zoom = 18,
        subdomains = '0123',
        name = 'NLS'
    ),
    JusticeMap = Bunch(
        income = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'income',
            name = 'JusticeMap.income'
        ),
        americanIndian = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'indian',
            name = 'JusticeMap.americanIndian'
        ),
        asian = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'asian',
            name = 'JusticeMap.asian'
        ),
        black = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'black',
            name = 'JusticeMap.black'
        ),
        hispanic = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'hispanic',
            name = 'JusticeMap.hispanic'
        ),
        multi = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'multi',
            name = 'JusticeMap.multi'
        ),
        nonWhite = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'nonwhite',
            name = 'JusticeMap.nonWhite'
        ),
        white = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'white',
            name = 'JusticeMap.white'
        ),
        plurality = TileProvider(
            url = 'http://www.justicemap.org/tile/{size}/{variant}/{z}/{x}/{y}.png',
            attribution = '<a href="http://www.justicemap.org/terms.php">Justice Map</a>',
            size = 'county',
            bounds = [[14, -180], [72, -56]],
            variant = 'plural',
            name = 'JusticeMap.plurality'
        )
    ),
    Wikimedia = TileProvider(
        url = 'https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}{r}.png',
        attribution = '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia</a>',
        min_zoom = 1,
        max_zoom = 19,
        name = 'Wikimedia'
    ),
    GeoportailFrance = Bunch(
        parcels = TileProvider(
            url = 'https://wxs.ign.fr/{apikey}/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER={variant}&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            attribution = '<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
            bounds = [[-75, -180], [81, 180]],
            min_zoom = 2,
            max_zoom = 20,
            apikey = 'choisirgeoportail',
            format = 'image/png',
            style = 'bdparcellaire',
            variant = 'CADASTRALPARCELS.PARCELS',
            name = 'GeoportailFrance.parcels'
        ),
        ignMaps = TileProvider(
            url = 'https://wxs.ign.fr/{apikey}/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER={variant}&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            attribution = '<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
            bounds = [[-75, -180], [81, 180]],
            min_zoom = 2,
            max_zoom = 18,
            apikey = 'choisirgeoportail',
            format = 'image/jpeg',
            style = 'normal',
            variant = 'GEOGRAPHICALGRIDSYSTEMS.MAPS',
            name = 'GeoportailFrance.ignMaps'
        ),
        maps = TileProvider(
            url = 'https://wxs.ign.fr/{apikey}/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER={variant}&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            attribution = '<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
            bounds = [[-75, -180], [81, 180]],
            min_zoom = 2,
            max_zoom = 18,
            apikey = 'choisirgeoportail',
            format = 'image/jpeg',
            style = 'normal',
            variant = 'GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD',
            name = 'GeoportailFrance.maps'
        ),
        orthos = TileProvider(
            url = 'https://wxs.ign.fr/{apikey}/geoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE={style}&TILEMATRIXSET=PM&FORMAT={format}&LAYER={variant}&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            attribution = '<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
            bounds = [[-75, -180], [81, 180]],
            min_zoom = 2,
            max_zoom = 19,
            apikey = 'choisirgeoportail',
            format = 'image/jpeg',
            style = 'normal',
            variant = 'ORTHOIMAGERY.ORTHOPHOTOS',
            name = 'GeoportailFrance.orthos'
        )
    ),
    OneMapSG = Bunch(
        Default = TileProvider(
            url = 'https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png',
            variant = 'Default',
            min_zoom = 11,
            max_zoom = 18,
            bounds = [[1.56073, 104.11475], [1.16, 103.502]],
            attribution = '<img src="https://docs.onemap.sg/maps/images/oneMap64-01.png" style="height:20px;width:20px;"/> New OneMap | Map data &copy; contributors, <a href="http://SLA.gov.sg">Singapore Land Authority</a>',
            name = 'OneMapSG.Default'
        ),
        Night = TileProvider(
            url = 'https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png',
            variant = 'Night',
            min_zoom = 11,
            max_zoom = 18,
            bounds = [[1.56073, 104.11475], [1.16, 103.502]],
            attribution = '<img src="https://docs.onemap.sg/maps/images/oneMap64-01.png" style="height:20px;width:20px;"/> New OneMap | Map data &copy; contributors, <a href="http://SLA.gov.sg">Singapore Land Authority</a>',
            name = 'OneMapSG.Night'
        ),
        Original = TileProvider(
            url = 'https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png',
            variant = 'Original',
            min_zoom = 11,
            max_zoom = 18,
            bounds = [[1.56073, 104.11475], [1.16, 103.502]],
            attribution = '<img src="https://docs.onemap.sg/maps/images/oneMap64-01.png" style="height:20px;width:20px;"/> New OneMap | Map data &copy; contributors, <a href="http://SLA.gov.sg">Singapore Land Authority</a>',
            name = 'OneMapSG.Original'
        ),
        Grey = TileProvider(
            url = 'https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png',
            variant = 'Grey',
            min_zoom = 11,
            max_zoom = 18,
            bounds = [[1.56073, 104.11475], [1.16, 103.502]],
            attribution = '<img src="https://docs.onemap.sg/maps/images/oneMap64-01.png" style="height:20px;width:20px;"/> New OneMap | Map data &copy; contributors, <a href="http://SLA.gov.sg">Singapore Land Authority</a>',
            name = 'OneMapSG.Grey'
        ),
        LandLot = TileProvider(
            url = 'https://maps-{s}.onemap.sg/v3/{variant}/{z}/{x}/{y}.png',
            variant = 'LandLot',
            min_zoom = 11,
            max_zoom = 18,
            bounds = [[1.56073, 104.11475], [1.16, 103.502]],
            attribution = '<img src="https://docs.onemap.sg/maps/images/oneMap64-01.png" style="height:20px;width:20px;"/> New OneMap | Map data &copy; contributors, <a href="http://SLA.gov.sg">Singapore Land Authority</a>',
            name = 'OneMapSG.LandLot'
        )
    )
)

